/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mc.gui;

import br.com.mc.facade.IFacade;
import br.com.mc.model.Midia;
import br.com.mc.util.DaoFactory;
import br.com.mc.util.MensagensUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Onismar
 */
public class BuscarMidia extends javax.swing.JDialog {

    /**
     * Creates new form Buscar
     */
    String opcao;
    DefaultTableModel modelo = new DefaultTableModel();
    IFacade facade = DaoFactory.createFacade();
    

    public BuscarMidia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    

    public int recuperaIdTabela() {

        int linha = -1;
        linha = tabela.getSelectedRow();
        if (linha >= 0) {
            int id = (Integer) tabela.getValueAt(linha, 0);
            return id;
        }
        return 0;

    }

    public void listar(String tipoLista) throws Exception {

        tabela.setRowHeight(25);
        modelo.setNumRows(0);

        List<Midia> listaMidia = new ArrayList<Midia>();

        if (tipoLista.equals("Mídias que não estão na Coleção")) {
            listaMidia = facade.naoEstaRealacionadoColecao();

        } else if (tipoLista.equals("Mídias que não estão em Compras Fututras")) {
            listaMidia = facade.naoEstaRealacionadoCompraFutura();

        } else {
            listaMidia = facade.listarMidia();
        }

        if (!listaMidia.isEmpty()) {

            for (int i = 0; i < listaMidia.size(); i++) {
                Vector linha = new Vector();
                linha.add(listaMidia.get(i).getId());
                linha.add(listaMidia.get(i).getTituloPortugues());
                linha.add(listaMidia.get(i).getTipoDeMidia());
                linha.add(listaMidia.get(i).getAnoDeLancamento());
                modelo.addRow(linha);

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBoxListar = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Mídia");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_coleção_p.png"))); // NOI18N
        jButton2.setText("Adicionar a Coleção");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_compra_futura.png"))); // NOI18N
        jButton7.setText("Compra Futura");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_more_info.png"))); // NOI18N
        jButton8.setText("Mais Informações");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBoxListar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxListar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Mídias que não estão na Coleção", "Mídias que não estão em Compras Fututras" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Listar:");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Listar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxListar, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxListar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (recuperaIdTabela() == 0) {
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE, "uma Mídia"));
        } else {

            if (!facade.estarRelacionadoColecao(recuperaIdTabela())) {

                if (!facade.estarRelacionadoCompraFutura(recuperaIdTabela())) {
                    try {
                        facade.inserirColecao(recuperaIdTabela());
                        JOptionPane.showMessageDialog(null,MensagensUtil.getValor(MensagensUtil.MSG_SUCESSO_SALVAR, "a sua Coleção"));
                        opcao = jComboBoxListar.getSelectedItem().toString();
                        listar(opcao);
                    } catch (Exception ex) {
                        Logger.getLogger(BuscarMidia.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    int op = JOptionPane.showConfirmDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_MIDIA_ESTA_EM_COMPRAS_FUTURAS), "Atenção!", 0, 2, null);
                    if (op == 0) {
                        try {
                            facade.removeCompraFutura(recuperaIdTabela());
                            facade.inserirColecao(recuperaIdTabela());
                            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_ADD_MIDIA, "a sua Coleção"));
                            opcao = jComboBoxListar.getSelectedItem().toString();
                            listar(opcao);
                        } catch (Exception ex) {
                            Logger.getLogger(BuscarMidia.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                }

            } else {
                JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_MIDIA_ESTA, "na sua Coleção"));
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if (recuperaIdTabela() == 0) {
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE, "uma Mídia") );
        } else {

            if (!facade.estarRelacionadoCompraFutura(recuperaIdTabela())) {

                if (!facade.estarRelacionadoColecao(recuperaIdTabela())) {
                    try {
                        facade.inserirCompraFutura(recuperaIdTabela());
                        JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_ADD_MIDIA, "a sua lista de compras futuras"));
                        opcao = jComboBoxListar.getSelectedItem().toString();
                        listar(opcao);
                    } catch (Exception ex) {
                        Logger.getLogger(BuscarMidia.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_MIDIA_ESTA, "na Coleção, e não pode ser adicionada em Compras Futuras"), "Atenção!", 2);
                }

            } else {
                JOptionPane.showMessageDialog(null,MensagensUtil.getValor(MensagensUtil.MSG_MIDIA_ESTA, "na sua lista de compras futuras") );
            }

        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        if (recuperaIdTabela() == 0) {
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE, "uma Mídia"));
        } else {
            TelaMidia.idMidia = recuperaIdTabela();
            TelaMidia tm = new TelaMidia(new javax.swing.JFrame(), true);
            tm.setVisible(true);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //Definindo as colunas da tabela
        modelo = (DefaultTableModel) tabela.getModel();

        //Adicionando as colunas    
        modelo.addColumn("Id");
        modelo.addColumn("Título");
        modelo.addColumn("Tipo de Mídia");
        modelo.addColumn("Ano de Lançamento");

        //Definindo o tamanho das colunas
        tabela.getColumnModel().getColumn(1).setPreferredWidth(280);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);

        //Definindo tamanho 0 a coluna ID
        tabela.getColumnModel().getColumn(0).setMinWidth(0);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabela.getColumnModel().getColumn(0).setMaxWidth(0);

        opcao = jComboBoxListar.getSelectedItem().toString();

        try {
            listar(opcao);
        } catch (Exception ex) {
            Logger.getLogger(BuscarMidia.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        opcao = jComboBoxListar.getSelectedItem().toString();

        try {
            listar(opcao);
        } catch (Exception ex) {
            Logger.getLogger(BuscarMidia.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarMidia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarMidia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarMidia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarMidia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarMidia dialog = new BuscarMidia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public static javax.swing.JComboBox jComboBoxListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
