/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mc.gui;

import br.com.mc.facade.IFacade;
import br.com.mc.model.Top10;
import br.com.mc.util.DaoFactory;
import br.com.mc.util.MensagensUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Onismar
 */
public class EditarTop10 extends javax.swing.JDialog {

    /**
     * Creates new form EditarTop10
     */
    public EditarTop10(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    DefaultTableModel modelo1, modelo2 = new DefaultTableModel();

    IFacade facade = DaoFactory.createFacade();

    List<Top10> listaTop10 = new ArrayList();
    List<Top10> listaTop10Serie = new ArrayList();

    public static int idMidia = 0;
    private static int posicao = 0;
    public static String tipoDeMidia = "";

    private ListarMidiaTop10 listarMidia;

    public void mostraDialog() {
        listarMidia = new ListarMidiaTop10(new javax.swing.JFrame(), true);
        listarMidia.setVisible(true);
    }

    public int recuperaIdTabelaFilme() {

        int linha = -1;
        linha = tabela1.getSelectedRow();
        if (linha >= 0) {
            int id = (Integer) tabela1.getValueAt(linha, 0);
            return id;
        }
        return 0;

    }

    public int recuperaIdTabelaSerie() {

        int linha = -1;
        linha = tabela2.getSelectedRow();
        if (linha >= 0) {
            int id = (Integer) tabela2.getValueAt(linha, 0);
            return id;
        }
        return 0;

    }

    public int recuperaPosTabelaFilme() {

        int linha = -1;
        linha = tabela1.getSelectedRow();
        if (linha >= 0) {
            int pos = (Integer) tabela1.getValueAt(linha, 1);
            return pos;
        }
        return 0;

    }

    public int recuperaPosTabelaSerie() {

        int linha = -1;
        linha = tabela2.getSelectedRow();
        if (linha >= 0) {
            int pos = (Integer) tabela2.getValueAt(linha, 1);
            return pos;
        }
        return 0;

    }

    public void listarFilme() {

        tabela1.setRowHeight(25);
        modelo1.setNumRows(0);
        String tipoMidia = "Filme";

        try {
            listaTop10 = facade.listarTop10(tipoMidia);
        } catch (Exception ex) {
            Logger.getLogger(EditarTop10.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (listaTop10 != null) {

            for (int i = 0; i < listaTop10.size(); i++) {
                Vector linha = new Vector();
                linha.add(listaTop10.get(i).getIdMidia());
                linha.add(listaTop10.get(i).getPosicao());
                linha.add(listaTop10.get(i).getTitulo());
                modelo1.addRow(linha);
            }

        }
    }

    public void listarSerie() {

        tabela2.setRowHeight(25);
        modelo2.setNumRows(0);
        String tipoMidia = "Série";

        try {
            listaTop10Serie = facade.listarTop10(tipoMidia);
        } catch (Exception ex) {
            Logger.getLogger(EditarTop10.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (listaTop10Serie != null) {

            for (int i = 0; i < listaTop10Serie.size(); i++) {
                Vector linha = new Vector();
                linha.add(listaTop10Serie.get(i).getIdMidia());
                linha.add(listaTop10Serie.get(i).getPosicao());
                linha.add(listaTop10Serie.get(i).getTitulo());
                modelo2.addRow(linha);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipoDeMidiaSelecionada = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        posicaoSelecionada = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar ao Top 10", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        tipoDeMidiaSelecionada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoDeMidiaSelecionada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Filme", "Série" }));

        jLabel3.setText("Tipo de Mídia:");

        titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setText("Título:");

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_buscar.png"))); // NOI18N
        jToggleButton2.setText("Buscar Mídia");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Posição:");

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_add_top10.png"))); // NOI18N
        jToggleButton3.setText("Adicionar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        posicaoSelecionada.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(10), Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipoDeMidiaSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(posicaoSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton3)))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jToggleButton3)
                    .addComponent(posicaoSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoDeMidiaSelecionada))
                .addGap(28, 28, 28))
        );

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela1);

        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabela2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Top 10 Filmes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Top 10 Séries");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_cancelar.png"))); // NOI18N
        jButton1.setText("Remover do Top 10");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_cancelar.png"))); // NOI18N
        jButton2.setText("Remover do Top 10");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int pos, id = 0;

        if (recuperaIdTabelaSerie() == 0) {
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_ERRO_REMOVER_TOP10," uma Série "));
        } else {

            try {
                facade.removeTop10(recuperaIdTabelaSerie());
                JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_REMOVER_TOP10," Série "));
                listaTop10Serie = facade.listarTop10("Série");
                for (int i = 0; i < listaTop10Serie.size(); i++) {

                    if (listaTop10Serie.get(i).getPosicao() > recuperaPosTabelaSerie()) {
                        pos = listaTop10Serie.get(i).getPosicao();
                        id = listaTop10Serie.get(i).getIdMidia();
                        facade.editarTop10(pos - 1, id);

                    }

                }
                listarSerie();
            } catch (Exception ex) {
                Logger.getLogger(EditarTop10.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int pos, id = 0;

        if (recuperaIdTabelaFilme() == 0) {
            JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_ERRO_ADD_TOP10," um Filme "));
        } else {

            try {
                facade.removeTop10(recuperaIdTabelaFilme());
                JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_REMOVER_TOP10," Filme "));
                listaTop10 = facade.listarTop10("Filme");
                for (int i = 0; i < listaTop10.size(); i++) {

                    if (listaTop10.get(i).getPosicao() > recuperaPosTabelaFilme()) {
                        pos = listaTop10.get(i).getPosicao();
                        id = listaTop10.get(i).getIdMidia();
                        facade.editarTop10(pos - 1, id);

                    }

                }
                listarFilme();
            } catch (Exception ex) {
                Logger.getLogger(EditarTop10.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        titulo.setEditable(false);

        //Tabela Filme
        modelo1 = (DefaultTableModel) tabela1.getModel();

        modelo1.addColumn("Id");
        modelo1.addColumn("Posição");
        modelo1.addColumn("Título");

        tabela1.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(2).setPreferredWidth(400);

        //Definindo tamanho 0 a coluna ID
        tabela1.getColumnModel().getColumn(0).setMinWidth(0);
        tabela1.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabela1.getColumnModel().getColumn(0).setMaxWidth(0);

        //Tabela Série
        modelo2 = (DefaultTableModel) tabela2.getModel();

        modelo2.addColumn("Id");
        modelo2.addColumn("Posição");
        modelo2.addColumn("Título");

        tabela2.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabela2.getColumnModel().getColumn(2).setPreferredWidth(400);

        //Definindo tamanho 0 a coluna ID
        tabela2.getColumnModel().getColumn(0).setMinWidth(0);
        tabela2.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabela2.getColumnModel().getColumn(0).setMaxWidth(0);

        listarFilme();
        listarSerie();


    }//GEN-LAST:event_formWindowOpened

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed

        posicao = (Integer) posicaoSelecionada.getValue();

        if (posicao != 0 && idMidia != 0) {

            int posAtual = 0;
            int idAtual = 0;

            if (tipoDeMidia.equals("Filme")) {
                if (facade.totalDeMidiasTop10("Filme")) {

                    if (!facade.estarRelacionadoTop10(idMidia)) {

                        for (int i = 0; i < listaTop10.size(); i++) {

                            if (listaTop10.get(i).getPosicao() >= posicao) {
                                posAtual = listaTop10.get(i).getPosicao();
                                idAtual = listaTop10.get(i).getIdMidia();
                                facade.editarTop10(posAtual + 1, idAtual);

                            }

                        }

                        try {
                            facade.inserirTop10(idMidia, posicao);
                            JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_ADD_TOP10," Filme "));
                            listarFilme();
                        } catch (Exception ex) {
                            Logger.getLogger(EditarTop10.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_ERRO_ADD_TOP10," O Filme" ));
                    }

                } else {
                    JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_TOP10_COMPLETO, " de Filme "));
                }

            } else {
                if (facade.totalDeMidiasTop10("Série")) {

                    if (!facade.estarRelacionadoTop10(idMidia)) {

                        for (int i = 0; i < listaTop10Serie.size(); i++) {

                            if (listaTop10Serie.get(i).getPosicao() >= posicao) {
                                posAtual = listaTop10Serie.get(i).getPosicao();
                                idAtual = listaTop10Serie.get(i).getIdMidia();
                                facade.editarTop10(posAtual + 1, idAtual);

                            }

                        }

                        try {
                            facade.inserirTop10(idMidia, posicao);
                            JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_ADD_TOP10," A Série "));
                            listarSerie();
                        } catch (Exception ex) {
                            Logger.getLogger(EditarTop10.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_ERRO_ADD_TOP10, " A Série"));
                    }

                } else {
                    JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_TOP10_COMPLETO, " de Série "));
                }
            }

            titulo.setText("");
            tipoDeMidiaSelecionada.setSelectedItem(null);
            posicaoSelecionada.setValue(0);

        } else {
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_ERRO_TOP10));
        }


    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

        tipoDeMidia = (String) tipoDeMidiaSelecionada.getSelectedItem();

        if (tipoDeMidia.equals("")) {
            JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE, " Filme ou Série! "));
          
        } else {

            if(titulo.getText().equals("")){
                mostraDialog();
            }
            else{
                titulo.setText("");
                posicaoSelecionada.setValue(0);
                idMidia = 0;
                mostraDialog();
            }
            
            

        }


    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarTop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarTop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarTop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarTop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarTop10 dialog = new EditarTop10(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JSpinner posicaoSelecionada;
    private javax.swing.JTable tabela1;
    private javax.swing.JTable tabela2;
    private javax.swing.JComboBox tipoDeMidiaSelecionada;
    public static javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
