/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mc.gui;

import br.com.mc.dao.ArtistaDAO;
import br.com.mc.dao.RelacionaElencoDAO;
import br.com.mc.facade.IFacade;
import br.com.mc.gui.CadastrarMidia;
import br.com.mc.model.Artista;
import br.com.mc.util.DaoFactory;
import br.com.mc.util.MensagensUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Onismar
 */
public class EditarElenco extends javax.swing.JDialog {

    /**
     * Creates new form EditarElenco
     */
   
    TelaArtista telaArtista;
    
    public static String profissao;
    private static int idMidia;
    public static int idArtista;
    DefaultTableModel modelo1, modelo2, modelo3 = new DefaultTableModel();

    IFacade facade = DaoFactory.createFacade();

    List<Artista> listaArtista = new ArrayList<Artista>();
    Artista art = new Artista();

    

    
    

    public EditarElenco(java.awt.Frame parent, boolean modal) {
             super(parent, modal);
             initComponents();
    }

    
    
    
    public static int getIdMidia() {
        return idMidia;
    }

    public static void setIdMidia(int idMidia) {
        EditarElenco.idMidia = idMidia;
    }
    
    
    
    public void mostraDialog() {
        telaArtista = new TelaArtista(new javax.swing.JFrame(), true);
        telaArtista.setVisible(true);
    }

    
    
    public void listarElenco() {

        tabela.setRowHeight(20);
        modelo1.setNumRows(0);

        List<Artista> listaArtista = new ArrayList<Artista>();

        try {
            System.out.println(idMidia);
            listaArtista = facade.retornaArtRelacionado(idMidia, "Ator/Atriz");
        } catch (Exception ex) {
            Logger.getLogger(EditarElenco.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        if (listaArtista != null) {

            for (int i = 0; i < listaArtista.size(); i++) {
                Vector linha = new Vector();
                linha.add(listaArtista.get(i).getId());
                linha.add(listaArtista.get(i).getNome());
                linha.add(listaArtista.get(i).getNomeNoFilme());
                modelo1.addRow(linha);

            }

        }
    }
    

    public void listarDiretor() {

        tabela2.setRowHeight(20);
        modelo2.setNumRows(0);

        List<Artista> listaArtista = new ArrayList<Artista>();

        try {
            System.out.println(idMidia);
            listaArtista = facade.retornaArtRelacionado(idMidia, "Diretor");
        } catch (Exception ex) {
            Logger.getLogger(EditarElenco.class.getName()).log(Level.SEVERE, null, ex);
        }

        //if(!listaArtista.isEmpty())
        if (listaArtista != null) {

            for (int i = 0; i < listaArtista.size(); i++) {
                Vector linha = new Vector();
                linha.add(listaArtista.get(i).getId());
                linha.add(listaArtista.get(i).getNome());
                modelo2.addRow(linha);

            }
        }
    }
    

    public void listarRoreirista() {

        tabela3.setRowHeight(25);
        modelo3.setNumRows(0);

        List<Artista> listaArtista = new ArrayList<Artista>();

        try {
            System.out.println(idMidia);
            listaArtista = facade.retornaArtRelacionado(idMidia, "Roteirista");
        } catch (Exception ex) {
            Logger.getLogger(EditarElenco.class.getName()).log(Level.SEVERE, null, ex);
        }

        //if(!listaArtista.isEmpty())
        if (listaArtista != null) {

            for (int i = 0; i < listaArtista.size(); i++) {
                Vector linha = new Vector();
                linha.add(listaArtista.get(i).getId());
                linha.add(listaArtista.get(i).getNome());
                modelo3.addRow(linha);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        personagem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        artista = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_cancelar.png"))); // NOI18N
        jButton1.setText("Remover Diretor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Elenco Principal");

        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabela2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Direção");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Roteiro");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_cancelar.png"))); // NOI18N
        jButton2.setText("Remover do Elenco");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabela3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabela3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_cancelar.png"))); // NOI18N
        jButton4.setText("Remover Roteirista");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar"));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_buscar.png"))); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        personagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Personagem:");

        artista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ator/Atriz", "Diretor", "Roteirista" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Adicionar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(artista, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(personagem, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artista, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personagem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_adicionarelenco.png"))); // NOI18N
        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(372, 372, 372))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(281, 281, 281))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(4, 4, 4)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        artista.setEditable(false);

        //Tabela Elenco   
        modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.addColumn("Id");
        modelo1.addColumn("Nome");
        modelo1.addColumn("Personagem");

        //Definindo tamanho 0 a coluna ID
        tabela.getColumnModel().getColumn(0).setMinWidth(0);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabela.getColumnModel().getColumn(0).setMaxWidth(0);

        //Tabela Diretor
        modelo2 = (DefaultTableModel) tabela2.getModel();
        modelo2.addColumn("Id");
        modelo2.addColumn("Nome");

        //Definindo tamanho 0 a coluna ID
        tabela2.getColumnModel().getColumn(0).setMinWidth(0);
        tabela2.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabela2.getColumnModel().getColumn(0).setMaxWidth(0);

        //Tabela Roteirista
        modelo3 = (DefaultTableModel) tabela3.getModel();
        modelo3.addColumn("Id");
        modelo3.addColumn("Nome");
        
         //Definindo tamanho 0 a coluna ID
        tabela3.getColumnModel().getColumn(0).setMinWidth(0);
        tabela3.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabela3.getColumnModel().getColumn(0).setMaxWidth(0);

        listarElenco();
        listarDiretor();
        listarRoreirista();


    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int linha = -1;
        linha = tabela.getSelectedRow();
        if (linha >= 0) {
            
            idArtista = (Integer) tabela.getValueAt(linha, 0);
            facade.removeRelacionamentoArtista(idMidia, idArtista);
            JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_REMOVER," Ator/Atriz "));
            listarElenco();
        } else {
            JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE," um Ator/Atriz "));
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        profissao = String.valueOf(EditarElenco.jComboBox1.getSelectedItem());
        mostraDialog();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (!artista.getText().equals("")) {

            if (profissao.equals("Ator/Atriz")) {
                
                if (!facade.estaRelacionado(idMidia, idArtista)) {
                    facade.realacionaArtista(idMidia,idArtista, personagem.getText());
                    listarElenco();
                    JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_ADD_ELENCO," O Ator/Atriz "));
                } else {
                    JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_ERRO_ADD_ELENCO," O Ator/Atriz "));
                }

            } else if (profissao.equals("Diretor")) {
                
                if (!facade.estaRelacionado(idMidia, idArtista)) {
                    facade.realacionaArtista(idMidia,idArtista,personagem.getText());
                    listarDiretor();
                    JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_ADD_ELENCO," O Diretor "));
                } else {
                    JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_ERRO_ADD_ELENCO," O Diretor "));
                }

            } else {
                
                if (!facade.estaRelacionado(idMidia, idArtista)) {
                    facade.realacionaArtista( idMidia,idArtista,personagem.getText());
                    listarRoreirista();
                    JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_ADD_ELENCO, " O Roteirista "));
                } else {
                    JOptionPane.showMessageDialog(null, MensagensUtil.getValor(MensagensUtil.MSG_ERRO_ADD_ELENCO, " O Roteirista "));
                }
            }

        }

        artista.setText("");
        personagem.setText("");


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int linha = -1;
        linha = tabela2.getSelectedRow();
        if (linha >= 0) {
            idArtista = (Integer) tabela2.getValueAt(linha, 0);
            facade.removeRelacionamentoArtista(idMidia, idArtista);
            JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_REMOVER," Diretor "));
            listarDiretor();
        } else {
            JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE," um Diretor "));
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int linha = -1;
        linha = tabela3.getSelectedRow();
        if (linha >= 0) {
            idArtista = (Integer) tabela3.getValueAt(linha, 0);
            facade.removeRelacionamentoArtista(idMidia, idArtista);
            JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_REMOVER," Roteirista "));
            listarRoreirista();
        } else {
            JOptionPane.showMessageDialog(null,  MensagensUtil.getValor(MensagensUtil.MSG_SELECIONE," um Roteirista "));
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarElenco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarElenco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarElenco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarElenco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarElenco dialog = new EditarElenco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField artista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public static javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField personagem;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabela2;
    private javax.swing.JTable tabela3;
    // End of variables declaration//GEN-END:variables
}
