/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mc.gui;

import br.com.mc.facade.IFacade;
import br.com.mc.model.Midia;
import br.com.mc.util.DaoFactory;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Onismar
 */
public class ListarMidiaTop10 extends javax.swing.JDialog {

    /**
     * Creates new form ListarMidiaTop10
     */
    public ListarMidiaTop10(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    DefaultTableModel modelo = new DefaultTableModel();
    IFacade facade = DaoFactory.createFacade();
    Midia m = new Midia();
    private static String tipoDeMidia = "";
    
    
    
    
    public int recuperaIdTabela() {

        int linha = -1;
        linha = tabela.getSelectedRow();
        if (linha >= 0) {
            int id = (Integer) tabela.getValueAt(linha, 0);
            return id;
        }
        return 0;

    }
    
    public String recuperaTituloMidia() {

        int linha = -1;
        linha = tabela.getSelectedRow();
        if (linha >= 0) {
            String titulo = (String) tabela.getValueAt(linha, 1);
            return titulo;
        }
        return "";

    }
    
    
    
    
    public void listar(){
        
        tabela.setRowHeight(25);
        modelo.setNumRows(0);
        
               
        
        List<Midia> listaMidia = new ArrayList<Midia>();
        
        
        try {
            listaMidia = facade.listarPorTipoMidia(tipoDeMidia);
        } catch (Exception ex) {
            Logger.getLogger(EditarMidia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if(!listaMidia.isEmpty()){  
            
            
             for(int i=0; i<listaMidia.size(); i++){
                 Vector linha = new Vector();
                 linha.add(listaMidia.get(i).getId());
                 linha.add(listaMidia.get(i).getTituloPortugues());
                 linha.add(listaMidia.get(i).getTipoDeMidia());
                 modelo.addRow(linha);
             
             }
        
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_novamidia.png"))); // NOI18N
        jToggleButton1.setText("Selecionar Mídia");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        //Obtendo o tipo de mídia a ser listado
        tipoDeMidia = EditarTop10.tipoDeMidia;
               
        //Definindo as colunas da tabela
        modelo = (DefaultTableModel) tabela.getModel(); 
              
        //Adicionando as colunas    
        modelo.addColumn("Id");
        modelo.addColumn("Título");
        modelo.addColumn("Tipo de Mídia");
               
        //Definindo o tamanho das colunas
        tabela.getColumnModel().getColumn(1).setPreferredWidth(500);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        
        
        //Definindo tamanho 0 a coluna ID
        tabela.getColumnModel().getColumn(0).setMinWidth(0);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabela.getColumnModel().getColumn(0).setMaxWidth(0);
        
        listar();
        
    }//GEN-LAST:event_formWindowOpened

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        if(recuperaIdTabela() == 0){
            JOptionPane.showMessageDialog(null, "Selecione uma Mídia");
        }
        else{
            
           EditarTop10.idMidia = recuperaIdTabela();
           EditarTop10.titulo.setText(recuperaTituloMidia());
           this.dispose();
           
            
        }
        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarMidiaTop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarMidiaTop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarMidiaTop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarMidiaTop10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListarMidiaTop10 dialog = new ListarMidiaTop10(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
