/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mc.gui;

import br.com.mc.facade.IFacade;
import br.com.mc.model.Artista;
import br.com.mc.model.Empresa;
import br.com.mc.model.Midia;
import br.com.mc.util.ConfiguracoesUtil;
import br.com.mc.util.DaoFactory;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Onismar
 */
public class TelaMidia extends javax.swing.JDialog {

    /**
     * Creates new form TelaMidia1
     */
    
    
     public static int idMidia;
    
    Midia m = new Midia();
    Empresa emp = new Empresa();
    Artista art = new Artista();
    DefaultTableModel modelo1, modelo2, modelo3 = new DefaultTableModel();
    
    IFacade facade = DaoFactory.createFacade();
    
    
    
    public TelaMidia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    
    
    public void listarElenco() {

        tabela1.setRowHeight(20);
        modelo1.setNumRows(0);

        List<Artista> listaArtista = new ArrayList<Artista>();

        try {
            
            listaArtista = facade.retornaArtRelacionado(idMidia, "Ator/Atriz");
        } catch (Exception ex) {
            Logger.getLogger(EditarElenco.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        if (listaArtista != null) {

            for (int i = 0; i < listaArtista.size(); i++) {
                Vector linha = new Vector();
                linha.add(listaArtista.get(i).getNome());
                linha.add(listaArtista.get(i).getNomeNoFilme());
                modelo1.addRow(linha);

            }

        }
    }

    public void listarDiretor() {

        tabela2.setRowHeight(20);
        modelo2.setNumRows(0);

        List<Artista> listaArtista = new ArrayList<Artista>();

        try {
            
            listaArtista = facade.retornaArtRelacionado(idMidia, "Diretor");
        } catch (Exception ex) {
            Logger.getLogger(EditarElenco.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (listaArtista != null) {

            for (int i = 0; i < listaArtista.size(); i++) {
                Vector linha = new Vector();
                linha.add(listaArtista.get(i).getNome());
                modelo2.addRow(linha);

            }
        }
    }

    public void listarRoreirista() {

        tabela3.setRowHeight(20);
        modelo3.setNumRows(0);

        List<Artista> listaArtista = new ArrayList<Artista>();

        try {
           
            listaArtista = facade.retornaArtRelacionado(idMidia, "Roteirista");
        } catch (Exception ex) {
            Logger.getLogger(EditarElenco.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (listaArtista != null) {

            for (int i = 0; i < listaArtista.size(); i++) {
                Vector linha = new Vector();
                linha.add(listaArtista.get(i).getNome());
                modelo3.addRow(linha);

            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titPort = new javax.swing.JLabel();
        titOrg = new javax.swing.JLabel();
        codBar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dur = new javax.swing.JLabel();
        pais = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        estudio = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        genero = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tipoEd = new javax.swing.JTextField();
        bd3d = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        dvd = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        loja = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        bd = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tipoEmb = new javax.swing.JTextField();
        anoLan = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        planoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mídia");
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        titPort.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(titPort);
        titPort.setBounds(170, 70, 590, 30);

        titOrg.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(titOrg);
        titOrg.setBounds(170, 100, 560, 22);

        codBar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        codBar.setText("A");
        getContentPane().add(codBar);
        codBar.setBounds(520, 150, 210, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Código de Barras:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 160, 109, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Direção:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(770, 300, 50, 15);

        dur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dur.setText("A");
        getContentPane().add(dur);
        dur.setBounds(550, 210, 140, 40);

        pais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pais.setText("A");
        getContentPane().add(pais);
        pais.setBounds(510, 240, 200, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("País de Origem:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(400, 250, 95, 17);

        estudio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        estudio.setText("A");
        getContentPane().add(estudio);
        estudio.setBounds(460, 300, 180, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Estúdio:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(400, 310, 50, 17);

        genero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        genero.setText("A");
        getContentPane().add(genero);
        genero.setBounds(460, 270, 140, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Gênero:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(400, 280, 49, 17);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Descrição:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(160, 400, 70, 15);

        descricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(descricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 420, 550, 80);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DVD");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(690, 590, 30, 20);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Local de Compra");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(960, 560, 120, 20);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("R$");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(840, 590, 20, 20);

        tipoEd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tipoEd);
        tipoEd.setBounds(130, 590, 100, 20);

        bd3d.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(bd3d);
        bd3d.setBounds(620, 590, 50, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Quantidade de Discos");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(570, 560, 160, 20);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("BD 3D");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(570, 590, 50, 20);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Tipo da Edição");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(130, 560, 100, 20);

        dvd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(dvd);
        dvd.setBounds(730, 590, 50, 20);

        valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(valor);
        valor.setBounds(860, 590, 50, 20);

        loja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(loja);
        loja.setBounds(960, 590, 110, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(110, 620, 970, 10);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/icone_cancelar.png"))); // NOI18N
        jButton2.setText("Fechar");
        jButton2.setMaximumSize(new java.awt.Dimension(165, 34));
        jButton2.setMinimumSize(new java.awt.Dimension(165, 34));
        jButton2.setPreferredSize(new java.awt.Dimension(165, 34));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(930, 630, 150, 34);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Valor da Edição");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(820, 560, 110, 20);

        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabela2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(770, 320, 270, 70);

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabela1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(770, 90, 270, 190);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Duracao (em minutos):");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(400, 220, 143, 17);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Elenco:");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(770, 70, 50, 15);

        bd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(bd);
        bd.setBounds(500, 590, 50, 20);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("BD");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(470, 590, 30, 20);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Tipo da Embalagem");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(290, 560, 140, 20);

        tipoEmb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tipoEmb);
        tipoEmb.setBounds(300, 590, 110, 20);

        anoLan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        anoLan.setText("A");
        getContentPane().add(anoLan);
        anoLan.setBounds(540, 180, 90, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Ano de Lançamento:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(400, 190, 128, 17);
        getContentPane().add(imagem);
        imagem.setBounds(170, 130, 200, 260);

        tabela3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabela3);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(770, 430, 270, 70);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Roteiro:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(770, 410, 50, 15);

        planoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/imagens/backgroud_tela_midia.png"))); // NOI18N
        getContentPane().add(planoDeFundo);
        planoDeFundo.setBounds(0, 0, 1200, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
         m = facade.retornaMidia(idMidia);
        
        titPort.setText(m.getTituloPortugues());
        titOrg.setText(m.getTituloOriginal());
        codBar.setText(m.getCodigoDeBarras());
        anoLan.setText(m.getAnoDeLancamento());
        dur.setText(m.getDuracao());
        pais.setText(m.getPaisDeOrigem());
        genero.setText(m.getGenero());
        descricao.setText(m.getDescricao());
        tipoEd.setText(m.getTipoDeEdicao());
        tipoEmb.setText(m.getTipoDeEmbalagem());
        bd.setText(String.valueOf(m.getQtdeBD()));
        bd3d.setText(String.valueOf(m.getQtdeBD3d()));
        dvd.setText(String.valueOf(m.getQtdeDvd()));
        valor.setText(String.valueOf(m.getValorDeCompra()));
        
        emp = facade.listaEmpRelacionada(idMidia, "Estúdio/TV");
        estudio.setText(emp.getNome());
        emp = facade.listaEmpRelacionada(idMidia, "Loja");
        loja.setText(emp.getNome());
        
        descricao.setEditable(false);
        tipoEd.setEditable(false);
        tipoEmb.setEditable(false);
        bd.setEditable(false);
        bd3d.setEditable(false);
        dvd.setEditable(false);
        valor.setEditable(false);
        loja.setEditable(false);
        
        
        ImageIcon img = new ImageIcon(ConfiguracoesUtil.getValor(ConfiguracoesUtil.DIRETORIO_DE_IMG) + m.getImagem());
        img.setImage(img.getImage().getScaledInstance(200, 257, 100)); 
        imagem.setIcon(img);
        
        
        //Tabela Elenco   
        modelo1 = (DefaultTableModel) tabela1.getModel();
        modelo1.addColumn("Nome");
        modelo1.addColumn("Personagem");
        
        
        //Tabela Diretor 
        modelo2 = (DefaultTableModel) tabela2.getModel();
        modelo2.addColumn("Nome");
        
        
        //Tabela Roteirista 
        modelo3 = (DefaultTableModel) tabela3.getModel();
        modelo3.addColumn("Nome");
        
        listarElenco();
        listarDiretor();
        listarRoreirista();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMidia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMidia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMidia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMidia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaMidia dialog = new TelaMidia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoLan;
    private javax.swing.JTextField bd;
    private javax.swing.JTextField bd3d;
    private javax.swing.JLabel codBar;
    private javax.swing.JTextPane descricao;
    private javax.swing.JLabel dur;
    private javax.swing.JTextField dvd;
    private javax.swing.JLabel estudio;
    private javax.swing.JLabel genero;
    private javax.swing.JLabel imagem;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField loja;
    private javax.swing.JLabel pais;
    private javax.swing.JLabel planoDeFundo;
    private javax.swing.JTable tabela1;
    private javax.swing.JTable tabela2;
    private javax.swing.JTable tabela3;
    private javax.swing.JTextField tipoEd;
    private javax.swing.JTextField tipoEmb;
    private javax.swing.JLabel titOrg;
    private javax.swing.JLabel titPort;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
